'use client'

import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { motion, AnimatePresence } from 'framer-motion'
import { Sparkles, RotateCcw, Check } from 'lucide-react'
import { Loader2 } from '@/components/ui/spinner'
import { Button } from '@/components/ui/button'
import type { BrandDNA } from '@/lib/brand-types'
import type { WizardAction } from '../hooks/useWizardState'
import {
  WIZARD_STEP_CONTAINER,
  WIZARD_STEP_CONTENT,
  WIZARD_TITLE,
  WIZARD_SUBTITLE,
  WIZARD_TEXTAREA,
  WIZARD_CARD,
  WIZARD_GHOST_BUTTON,
} from '../brandStudioStyles'

interface BrandContextStepProps {
  draft: Partial<BrandDNA>
  dispatch: React.Dispatch<WizardAction>
  onGenerate?: () => void
  isGenerating?: boolean
}

export function BrandContextStep({
  draft,
  dispatch,
  onGenerate,
  isGenerating = false,
}: BrandContextStepProps) {
  const { t } = useTranslation('brandStudio')

  // Local context text
  const [contextText, setContextText] = useState(
    draft.text_assets?.brand_context || draft.business_overview || ''
  )

  // Suggestions generated by AI
  const [suggestions, setSuggestions] = useState<string[]>([])

  // Re-init from draft
  useEffect(() => {
    const ctx = draft.text_assets?.brand_context || draft.business_overview
    if (ctx && !contextText) setContextText(ctx)
  }, [draft.text_assets?.brand_context, draft.business_overview, contextText])

  // Sync context back to draft
  const handleTextChange = (value: string) => {
    setContextText(value)
    dispatch({ 
      type: 'UPDATE_DRAFT', 
      data: { 
        text_assets: { 
          ...draft.text_assets,
          brand_context: value 
        } 
      } as Partial<BrandDNA> 
    })
  }

  const handleUseSuggestion = (suggestion: string) => {
    setContextText(suggestion)
    dispatch({ 
      type: 'UPDATE_DRAFT', 
      data: { 
        text_assets: { 
          ...draft.text_assets,
          brand_context: suggestion 
        } 
      } as Partial<BrandDNA> 
    })
  }

  return (
    <div className={WIZARD_STEP_CONTAINER}>
      <div className={WIZARD_STEP_CONTENT}>
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="space-y-2"
        >
          <h1 className={WIZARD_TITLE}>{t('brandContext.title')}</h1>
          <p className={WIZARD_SUBTITLE}>{t('brandContext.subtitle')}</p>
        </motion.div>

        {/* Editable textarea */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15, duration: 0.4 }}
        >
          <textarea
            value={contextText}
            onChange={(e) => handleTextChange(e.target.value)}
            placeholder={t('brandContext.textareaPlaceholder')}
            rows={6}
            className={WIZARD_TEXTAREA}
          />
        </motion.div>

        {/* Generate button */}
        {onGenerate && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.25, duration: 0.3 }}
            className="flex justify-center"
          >
            <Button
              variant="outline"
              onClick={onGenerate}
              disabled={isGenerating}
              className={`${WIZARD_GHOST_BUTTON} gap-2`}
            >
              {isGenerating ? (
                <Loader2 className="h-4 w-4" />
              ) : contextText ? (
                <RotateCcw className="h-4 w-4" />
              ) : (
                <Sparkles className="h-4 w-4" />
              )}
              {isGenerating
                ? t('brandContext.generating')
                : contextText
                  ? t('brandContext.regenerateBtn')
                  : t('brandContext.generateBtn')}
            </Button>
          </motion.div>
        )}

        {/* Suggestions */}
        <AnimatePresence>
          {suggestions.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="space-y-3"
            >
              <p className="text-sm font-medium uppercase tracking-wider text-muted-foreground/60">
                {t('brandContext.suggestionsLabel')}
              </p>
              <div className="space-y-2">
                {suggestions.map((s, i) => (
                  <motion.button
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.05 }}
                    className={`${WIZARD_CARD} w-full cursor-pointer`}
                    onClick={() => handleUseSuggestion(s)}
                  >
                    <div className="flex items-start gap-3">
                      <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary/50" />
                      <p className="text-sm text-muted-foreground leading-relaxed text-left">{s}</p>
                    </div>
                  </motion.button>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}
