import {
    STUDIO_CANVAS_FLOATING_TOOLBAR_CLASS,
    STUDIO_CANVAS_OVERLAY_BUTTON_CLASS,
    STUDIO_CANVAS_REMOVE_BUTTON_CLASS,
    STUDIO_CANVAS_TOOL_BUTTON_CLASS,
    STUDIO_CANVAS_TOOL_VALUE_CLASS,
} from '@/components/studio/shared/canvasStyles'

export const CANVAS_FLOATING_TOOLBAR_CLASS = STUDIO_CANVAS_FLOATING_TOOLBAR_CLASS
export const CANVAS_TOOL_BUTTON_CLASS = STUDIO_CANVAS_TOOL_BUTTON_CLASS
export const CANVAS_OVERLAY_BUTTON_CLASS = STUDIO_CANVAS_OVERLAY_BUTTON_CLASS
export const CANVAS_REMOVE_BUTTON_CLASS = STUDIO_CANVAS_REMOVE_BUTTON_CLASS
export const CANVAS_TOOL_VALUE_CLASS = STUDIO_CANVAS_TOOL_VALUE_CLASS
export const CANVAS_TOOL_ICON_CLASS = '!h-8 !w-8'
